/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OuvidoriaRouteImport } from './routes/ouvidoria'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSecretariasRouteImport } from './routes/_authenticated/secretarias'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProtocolosRouteImport } from './routes/_authenticated/protocolos'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedEmailInboxRouteImport } from './routes/_authenticated/email-inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAtrasadosRouteImport } from './routes/_authenticated/atrasados'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios.index'
import { Route as AuthenticatedProtocolosAntigosIndexRouteImport } from './routes/_authenticated/protocolos-antigos.index'
import { Route as ApiPublicGmailSyncRouteImport } from './routes/api/public/gmail-sync'
import { Route as ApiPublicEmailSyncRouteImport } from './routes/api/public/email-sync'
import { Route as ApiPublicInboundEmailTokenRouteImport } from './routes/api/public/inbound-email.$token'
import { Route as AuthenticatedRelatoriosSecretariaIdRouteImport } from './routes/_authenticated/relatorios.secretaria.$id'
import { Route as AuthenticatedProtocolosAntigosSourceNumeroRouteImport } from './routes/_authenticated/protocolos-antigos.$source.$numero'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoriaRoute = OuvidoriaRouteImport.update({
  id: '/ouvidoria',
  path: '/ouvidoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecretariasRoute =
  AuthenticatedSecretariasRouteImport.update({
    id: '/secretarias',
    path: '/secretarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProtocolosRoute = AuthenticatedProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailInboxRoute = AuthenticatedEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtrasadosRoute = AuthenticatedAtrasadosRouteImport.update({
  id: '/atrasados',
  path: '/atrasados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedProtocolosAntigosIndexRoute =
  AuthenticatedProtocolosAntigosIndexRouteImport.update({
    id: '/protocolos-antigos/',
    path: '/protocolos-antigos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGmailSyncRoute = ApiPublicGmailSyncRouteImport.update({
  id: '/api/public/gmail-sync',
  path: '/api/public/gmail-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailSyncRoute = ApiPublicEmailSyncRouteImport.update({
  id: '/api/public/email-sync',
  path: '/api/public/email-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailTokenRoute =
  ApiPublicInboundEmailTokenRouteImport.update({
    id: '/api/public/inbound-email/$token',
    path: '/api/public/inbound-email/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRelatoriosSecretariaIdRoute =
  AuthenticatedRelatoriosSecretariaIdRouteImport.update({
    id: '/secretaria/$id',
    path: '/secretaria/$id',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedProtocolosAntigosSourceNumeroRoute =
  AuthenticatedProtocolosAntigosSourceNumeroRouteImport.update({
    id: '/protocolos-antigos/$source/$numero',
    path: '/protocolos-antigos/$source/$numero',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atrasados': typeof AuthenticatedAtrasadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/protocolos': typeof AuthenticatedProtocolosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/saude': typeof AuthenticatedSaudeRoute
  '/secretarias': typeof AuthenticatedSecretariasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/email-sync': typeof ApiPublicEmailSyncRoute
  '/api/public/gmail-sync': typeof ApiPublicGmailSyncRoute
  '/protocolos-antigos/': typeof AuthenticatedProtocolosAntigosIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/protocolos-antigos/$source/$numero': typeof AuthenticatedProtocolosAntigosSourceNumeroRoute
  '/relatorios/secretaria/$id': typeof AuthenticatedRelatoriosSecretariaIdRoute
  '/api/public/inbound-email/$token': typeof ApiPublicInboundEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atrasados': typeof AuthenticatedAtrasadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/protocolos': typeof AuthenticatedProtocolosRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/secretarias': typeof AuthenticatedSecretariasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/email-sync': typeof ApiPublicEmailSyncRoute
  '/api/public/gmail-sync': typeof ApiPublicGmailSyncRoute
  '/protocolos-antigos': typeof AuthenticatedProtocolosAntigosIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/protocolos-antigos/$source/$numero': typeof AuthenticatedProtocolosAntigosSourceNumeroRoute
  '/relatorios/secretaria/$id': typeof AuthenticatedRelatoriosSecretariaIdRoute
  '/api/public/inbound-email/$token': typeof ApiPublicInboundEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/atrasados': typeof AuthenticatedAtrasadosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-inbox': typeof AuthenticatedEmailInboxRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/protocolos': typeof AuthenticatedProtocolosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/_authenticated/secretarias': typeof AuthenticatedSecretariasRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/email-sync': typeof ApiPublicEmailSyncRoute
  '/api/public/gmail-sync': typeof ApiPublicGmailSyncRoute
  '/_authenticated/protocolos-antigos/': typeof AuthenticatedProtocolosAntigosIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/protocolos-antigos/$source/$numero': typeof AuthenticatedProtocolosAntigosSourceNumeroRoute
  '/_authenticated/relatorios/secretaria/$id': typeof AuthenticatedRelatoriosSecretariaIdRoute
  '/api/public/inbound-email/$token': typeof ApiPublicInboundEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/ouvidoria'
    | '/reset-password'
    | '/atrasados'
    | '/dashboard'
    | '/email-inbox'
    | '/mapa'
    | '/protocolos'
    | '/relatorios'
    | '/saude'
    | '/secretarias'
    | '/users'
    | '/api/public/email-sync'
    | '/api/public/gmail-sync'
    | '/protocolos-antigos/'
    | '/relatorios/'
    | '/protocolos-antigos/$source/$numero'
    | '/relatorios/secretaria/$id'
    | '/api/public/inbound-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/ouvidoria'
    | '/reset-password'
    | '/atrasados'
    | '/dashboard'
    | '/email-inbox'
    | '/mapa'
    | '/protocolos'
    | '/saude'
    | '/secretarias'
    | '/users'
    | '/api/public/email-sync'
    | '/api/public/gmail-sync'
    | '/protocolos-antigos'
    | '/relatorios'
    | '/protocolos-antigos/$source/$numero'
    | '/relatorios/secretaria/$id'
    | '/api/public/inbound-email/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/ouvidoria'
    | '/reset-password'
    | '/_authenticated/atrasados'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-inbox'
    | '/_authenticated/mapa'
    | '/_authenticated/protocolos'
    | '/_authenticated/relatorios'
    | '/_authenticated/saude'
    | '/_authenticated/secretarias'
    | '/_authenticated/users'
    | '/api/public/email-sync'
    | '/api/public/gmail-sync'
    | '/_authenticated/protocolos-antigos/'
    | '/_authenticated/relatorios/'
    | '/_authenticated/protocolos-antigos/$source/$numero'
    | '/_authenticated/relatorios/secretaria/$id'
    | '/api/public/inbound-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OuvidoriaRoute: typeof OuvidoriaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicEmailSyncRoute: typeof ApiPublicEmailSyncRoute
  ApiPublicGmailSyncRoute: typeof ApiPublicGmailSyncRoute
  ApiPublicInboundEmailTokenRoute: typeof ApiPublicInboundEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvidoria': {
      id: '/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/ouvidoria'
      preLoaderRoute: typeof OuvidoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretarias': {
      id: '/_authenticated/secretarias'
      path: '/secretarias'
      fullPath: '/secretarias'
      preLoaderRoute: typeof AuthenticatedSecretariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocolos': {
      id: '/_authenticated/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof AuthenticatedProtocolosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-inbox': {
      id: '/_authenticated/email-inbox'
      path: '/email-inbox'
      fullPath: '/email-inbox'
      preLoaderRoute: typeof AuthenticatedEmailInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atrasados': {
      id: '/_authenticated/atrasados'
      path: '/atrasados'
      fullPath: '/atrasados'
      preLoaderRoute: typeof AuthenticatedAtrasadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/protocolos-antigos/': {
      id: '/_authenticated/protocolos-antigos/'
      path: '/protocolos-antigos'
      fullPath: '/protocolos-antigos/'
      preLoaderRoute: typeof AuthenticatedProtocolosAntigosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/gmail-sync': {
      id: '/api/public/gmail-sync'
      path: '/api/public/gmail-sync'
      fullPath: '/api/public/gmail-sync'
      preLoaderRoute: typeof ApiPublicGmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-sync': {
      id: '/api/public/email-sync'
      path: '/api/public/email-sync'
      fullPath: '/api/public/email-sync'
      preLoaderRoute: typeof ApiPublicEmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email/$token': {
      id: '/api/public/inbound-email/$token'
      path: '/api/public/inbound-email/$token'
      fullPath: '/api/public/inbound-email/$token'
      preLoaderRoute: typeof ApiPublicInboundEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios/secretaria/$id': {
      id: '/_authenticated/relatorios/secretaria/$id'
      path: '/secretaria/$id'
      fullPath: '/relatorios/secretaria/$id'
      preLoaderRoute: typeof AuthenticatedRelatoriosSecretariaIdRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/protocolos-antigos/$source/$numero': {
      id: '/_authenticated/protocolos-antigos/$source/$numero'
      path: '/protocolos-antigos/$source/$numero'
      fullPath: '/protocolos-antigos/$source/$numero'
      preLoaderRoute: typeof AuthenticatedProtocolosAntigosSourceNumeroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
  AuthenticatedRelatoriosSecretariaIdRoute: typeof AuthenticatedRelatoriosSecretariaIdRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
    AuthenticatedRelatoriosSecretariaIdRoute:
      AuthenticatedRelatoriosSecretariaIdRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtrasadosRoute: typeof AuthenticatedAtrasadosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailInboxRoute: typeof AuthenticatedEmailInboxRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedProtocolosRoute: typeof AuthenticatedProtocolosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedSecretariasRoute: typeof AuthenticatedSecretariasRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedProtocolosAntigosIndexRoute: typeof AuthenticatedProtocolosAntigosIndexRoute
  AuthenticatedProtocolosAntigosSourceNumeroRoute: typeof AuthenticatedProtocolosAntigosSourceNumeroRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtrasadosRoute: AuthenticatedAtrasadosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailInboxRoute: AuthenticatedEmailInboxRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedProtocolosRoute: AuthenticatedProtocolosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedSecretariasRoute: AuthenticatedSecretariasRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedProtocolosAntigosIndexRoute:
    AuthenticatedProtocolosAntigosIndexRoute,
  AuthenticatedProtocolosAntigosSourceNumeroRoute:
    AuthenticatedProtocolosAntigosSourceNumeroRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OuvidoriaRoute: OuvidoriaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicEmailSyncRoute: ApiPublicEmailSyncRoute,
  ApiPublicGmailSyncRoute: ApiPublicGmailSyncRoute,
  ApiPublicInboundEmailTokenRoute: ApiPublicInboundEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
